name: dart_bs58
description: Dart component to compute base 58 encoding. This encoding is typically used for cryptocurrencies such as Bitcoin.
version: 1.0.1
homepage: https://www.github.com/dart-bitcoin-lib/dart_bs58
repository: https://www.github.com/dart-bitcoin-lib/dart_bs58
issue_tracker: https://www.github.com/dart-bitcoin-lib/dart_bs58/issues

environment:
  sdk: '>=2.12.0 <3.0.0'


dev_dependencies:
  convert: ^3.0.1
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  dart_base_x: ^1.0.0
